json.id grid.id
json.code grid.code
json.name grid.name
json.owner grid.user_id
json.users grid.has_square
json.rows_digit grid.rows_digit
json.columns_digit grid.columns_digit
json.created_at grid.created_at
json.updated_at grid.updated_at